apiVersion: v1
kind: Service
metadata:
  name: juanberger-service
spec:
  selector:
    app: juanberger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30004
  type: LoadBalancer
